### ISSUE TITLE
Crash again

### ISSUE THREAD

**Issue by BlearOsprey1107** [Thutmose/Pokecube#218] opened 2017-09-28 10:08 UTC
After the mod is updated i can play a bit but then it crash again

**Comment by Thutmose** [comment] 2017-09-28 14:27
you need to incude crash reports or logs, just saying it crashes is useless.

**Comment by Farsinuce** [comment] 2017-09-30 14:42
I'll just continue BlearOsprey's issue here, since I am also experiencing a client crash after updating.

Here's a crashlog:
[crash-2017-09-30_16.24.37-client.txt](https://github.com/Thutmose/Pokecube/files/1346474/crash-2017-09-30_16.24.37-client.txt)

These are my mod versions:
[mods_list.txt](https://github.com/Thutmose/Pokecube/files/1346476/mods_list.txt)

I am running MC 1.12, Forge 14.21.1.2443.

Thank you for your time, @Thutmose.

UPDATE:
To bugtrace, I Just tried to downgrade Pokecube Core 2.21.2 and Pokecube Mobs 2.14.10 to version 2.21.1 and 2.14.7 respectively. Didn't help. Am confused.

**Comment by Thutmose** [comment] 2017-09-30 15:06
hmm, i suspect the issue is related to an update in forge, which seems to require thutcore to be recompiled, I recompiled thutcore for 1.12.1 and 1.12.2, to fix that exact crash for it.

**Comment by Farsinuce** [comment] 2017-09-30 15:07
Oh, I am however using the same Forge version ("latest" 14.21.1.2443 for MC 1.12).

I will try to downgrade Thutcore to 5.11.0.
Just a sec :)

**Comment by Thutmose** [comment] 2017-09-30 15:10
I think that version of thutcore was compiled for an earlier version of 1.12 forge, and the later version changed something, is there any reason you can't update to 1.12.2 or 1.12.1?

**Comment by Farsinuce** [comment] 2017-09-30 15:12
Yeah, I have a couple of old mods that are not made for 1.12.x 😞 

But thanks! Downgrading thutcore from 5.11.1 to 5.11.0 worked 😃 

EDIT:
Maybe the solution is the same for you, @BlearOsprey1107

**Comment by Thutmose** [comment] 2017-09-30 15:15
ok, I will remove 5.11.1 from the list in the mean time then, since it no longer works with latest forge for whatever reason... 

which of the mods isn't for 1.12.x? did you try them in later versions, some mods work even if they were not made for it

**Comment by Farsinuce** [comment] 2017-09-30 15:35
> which of the mods isn't for 1.12.x? did you try them in later versions, some mods work even if they were not made for it

That would be [LLOverlayReloaded](https://minecraft.curseforge.com/projects/light-level-overlay-reloaded)...
I just checked [GlobalXP](https://minecraft.curseforge.com/projects/global-xp), but it does indeed have a 1.12.1 version after all.

And no, I have not tried them in later versions. I just assumed that mods would only work in the exact MC version, that they were compiled for 😮

**Comment by Thutmose** [comment] 2017-10-11 23:50
closing this issue since the initial cause was fixed via recompile.

**Closed as completed by Thutmose** 2017-10-11 23:50 UTC
