### ISSUE TITLE
teleported to unsafe location - suffocated and threw exceptions

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Pokecube#230] opened 2017-11-11 02:33 UTC
#### Issue Description:
Note: exception is thrown to the server/logs during death of player.  Teleported to unsafe location and died.  The server stayed alive, but threw exception during the player death event.

#### What happens:
I teleported to a location on the world which put me into a mountain and suffocated and died.  

#### What you expected to happen:
This is as expected, but the logs https://pastebin.com/QgD42ehL show that it wasn't handled as gracefully as it could have.

#### Steps to reproduce:
1. Teleport underground or into a mountain and die.
2. Look at server console for attached errors

#### Affected Versions (Do *not* use "latest"):
- Pokecube Core: 6.23.3
- Pokecube Revival (if applicable): 6.13.2
- Pokecube Mobs (if applicable): 4.1.2
- thut_bling: 2.0.1
- thut_wearables: 3.1.2
- thut_core: 5.11.7
- thutpermissions: 2.0.0
- thutessentials-2.1.3
- dynmap-2.6-beta-1-forge-1.12
- worldedit-forge-mc1.12-6.1.8-dist
- Minecraft: 1.12.2
- Forge: 1.12.2 (1.12.2-14.23.0.2528)

#### Desired results:
Player should indeed die, be notified he/she died, but no exceptions should be thrown in the process.

**Comment by Thutmose** [comment] 2017-11-11 06:10
This is caused by: **https://github.com/SpongePowered/SpongeForge/issues/1810**

Note that is also probably deleted one or two of your pokemobs in the mean time.

**Comment by smmmadden** [comment] 2017-11-14 02:42
yes it did, lost the inventory because I couldn't get back to where I suffocated.  No biggy, still learning this stuff and upgraded the Sponge server to build 2538.  Hopefully it won't happen again.  Thanks!

**Comment by smmmadden** [comment] 2017-11-14 03:07
just got slain by a wild rattata and threw the same lengthy exception trying to unwind the deathphase.  So much for build 2538.

**Comment by Thutmose** [comment] 2017-11-14 03:44
sponge never marked it as fixed, so the bug is still probably still there

**Comment by Thutmose** [comment] 2018-01-10 13:18
This issue is partially fixed by sponge (tested in 2831), enough for me to close the issue, hopefully they will finish off the fix later.

Thier fix now results in the pokemob exiting the cube when tossed, instead of going to PC.

**Closed as completed by Thutmose** 2018-01-10 13:18 UTC
Labels: SPONGE
