### ISSUE TITLE
Crash generating a village

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#133] opened 2016-08-14 20:17 UTC
#### Issue Description:

the game crashed when i was walking
#### What happens:

looks like it crashed because it failed to generate a village i am using the more villages mod too so it may be related
https://gist.github.com/jochuan/6ed2275fc0af074587fff99ce29900f3
#### What you expected to happen:

the game should not crash
#### Steps to reproduce:

1.walk until the game generates a village i think

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.7.7
- Pokecube Revival (if applicable):3.6.6
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:2051

**Comment by jochuan** [comment] 2016-08-14 20:52
after the crash the village only generated the pokecenter and pokemart and the well without any villagers or npcs
![2016-08-14_17 42 35](https://cloud.githubusercontent.com/assets/11268912/17651955/99e771c6-6247-11e6-8bc1-a5c145260f60.png)
![2016-08-14_17 42 39](https://cloud.githubusercontent.com/assets/11268912/17651956/9be602f8-6247-11e6-9c76-39805b223c3b.png)
![2016-08-14_17 42 46](https://cloud.githubusercontent.com/assets/11268912/17651957/9d9d511e-6247-11e6-85b2-0bc316b3a2aa.png)

**Comment by Thutmose** [comment] 2016-08-14 21:04
Hmm, that is odd, I wonder if a newer version of forge for 1.9.4 changed something?

**Comment by Thutmose** [comment] 2016-08-14 21:05
I will look into this and try to get it fixed shortly

**Comment by Thutmose** [comment] 2016-08-14 21:10
I will test with forge 2051, it doesn't seem to occur in my testing environment when I use 1976

**Comment by Thutmose** [comment] 2016-08-14 21:17
Can you see if you can get it to replicate with just pokecube stuff in your minecraft? it might be somehow caused by one of your mods

**Comment by jochuan** [comment] 2016-08-14 21:22
yes like i said before it must be more villages mod conflicting with pokecube
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2641558-mo-villages-v1-5-2-for-1-9-and-v1-5-2-for-1-9-4
but i will test with only pokecube to see if it happens

**Comment by jochuan** [comment] 2016-08-14 22:14
i tested with only pokecube on a seed with a village on spawn and the game crashed too

**Comment by jochuan** [comment] 2016-08-15 21:22
i tested with 1976 and it happens too

**Comment by Thutmose** [comment] 2016-08-16 21:28
This should be fixed in the version I just uploaded to curse (3.7.8)

**Closed as completed by Thutmose** 2016-08-16 21:28 UTC
Labels: Major Bug, 1.9.4 only
