### ISSUE TITLE
Crashes when I try to equip pokewatch or bag in thut wearables

### ISSUE THREAD

**Issue by smitheri6** [Thutmose/Pokecube#312] opened 2018-08-08 17:14 UTC
https://pastebin.com/651U8TC4
here is the crash report

#### Issue Description:
Every time I try to equip a pokewatch or a bag to my thuts wearable slots, my game crashes and I lose the item I tried to equip permanently. However, if I get a bag from creative mod, I get my items that was inside it back. I am not using Pokecube AIO, and I am using the versions right before the newest versions updated a day ago. (because if I use the newest versions my game says that pokemobs needs pokecube adventures to work, which I cannot find)

#### What happens:

My game crashes immediately as I shift+left click the watch to go to my thut wearable slot or if I try to click and drag it to the appropriate slot. 

#### What you expected to happen:

I expect the item to be placed in my slot without the game crashing and then have the ability to use said item 

#### Steps to reproduce:

1. Open Pokecube version before the newest version, without pokecube AIO
2.open inventory and open the thut wearbles button in the top left corner of the character view
3. obtain a pokewatch or bag from Pokecube Revival and either shift+left click or click and drag the item to the appropriate slot (the watch looking slot of the bag looking slot)
4. watch your game immediately crash and discover that the item you tried to equip is gone

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:1.12.2-6.4.5
- Pokecube Revival (if applicable):1.12.2-6.15.4
- Pokecube Mobs (if applicable):1.12.2-4.10.2
- Minecraft: 1.12.2
- Forge:1.12.2-14.23.4.2726

**Comment by Thutmose** [comment] 2018-08-08 22:56
Try updating to wearables 3.2.0, see if that fixes it, it should be available at this link as soon as it is approved on curseforge: https://minecraft.curseforge.com/projects/thut-wearables/files/2600171

**Comment by smitheri6** [comment] 2018-08-09 00:21
Thank you. I will have to try it tomorrow. My wife is home now and she wants to hang out.

**Comment by Thutmose** [comment] 2018-08-09 00:21
No worries, just let me know when you do get around to testing it

**Comment by smitheri6** [comment] 2018-08-09 14:57
It works! Thank you!

**Comment by smitheri6** [comment] 2018-08-09 15:19
One more thing, do you have a guide anywhere that explains how to evolve
certain pokemon with certain evolution requirements? Rockruff wont evolve
at lvl 25, there is no razor claw so sneasle cant evolve into wevile,
magnazone needs to evolve inn a certain area, etc. Can you explain any of
that?

**Comment by Thutmose** [comment] 2018-08-10 00:08
closing this issue since it was fixed.  Check JEI for your question on evolution, more details are here:

https://youtu.be/UijGJnbAXBQ

**Closed as completed by Thutmose** 2018-08-10 00:08 UTC

**Comment by smitheri6** [comment] 2018-08-11 23:11
Hey, so there are some broken textures for the pokemobs, like Heliolisk.
They just look like Missing No. This is on the newest version of POkecube
AIO and the other versions you were helping me with the other day. Did you
have plans on fixing that?

**Comment by Thutmose** [comment] 2018-08-11 23:34
this is a feature, not a bug.  If it looks like a missingno, it means noone has sent me a model for it, I only have models that are sent in by others, so I cannot add a model if they do not sent it in

**Comment by smitheri6** [comment] 2018-08-12 16:24
Okay then. By they way, thanks for putting all of this together. It is really fun to play pokemon in Minecraft and I know it takes a lot of effort. Thank you.

**Comment by Thutmose** [comment] 2018-08-12 18:03
No problem, I mostly do this as a hobby, it is something I use to relax.
