### ISSUE TITLE
Crash when defeating NPC or Offline-Player-Owned Pokemob, While running with Sponge.

### ISSUE THREAD

**Issue by Hellcommander** [Thutmose/Pokecube#191] opened 2017-07-17 09:45 UTC
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:

 Noibat scored a critical hit at which point the game crashed.
he is part of the crash log for easy reading and I'll attach the full crash.
`Time: 7/17/17 5:34 AM
Description: Ticking entity

java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.returnToPokecube(EntityTameablePokemob.java:749)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70609_aI(EntityAiPokemob.java:759)
	at net.minecraft.entity.EntityLivingBase.onSpongeDeathUpdate(EntityLivingBase.java:3856)
	at net.minecraft.entity.EntityLivingBase.redirect$causeTrackDeathUpdate$zde000(EntityLivingBase.java:3846)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:280)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2081)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:567)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:455)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:359)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:175)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:803)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:610)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkg000(WorldServer.java:2868)
	at net.minecraft.world.World.func_72866_a(World.java:1976)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1939)
	at net.minecraft.world.World.func_72939_s(World.java:6032)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2205)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at jds.bibliocraft.events.EventItemToss.DroppedItemEvent(EventItemToss.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_253_EventItemToss_DroppedItemEvent_ItemTossEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:646)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.returnToPokecube(EntityTameablePokemob.java:749)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70609_aI(EntityAiPokemob.java:759)
	at net.minecraft.entity.EntityLivingBase.onSpongeDeathUpdate(EntityLivingBase.java:3856)
	at net.minecraft.entity.EntityLivingBase.redirect$causeTrackDeathUpdate$zde000(EntityLivingBase.java:3846)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:280)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2081)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:567)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:455)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:359)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:175)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:803)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:317)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:610)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkg000(WorldServer.java:2868)
	at net.minecraft.world.World.func_72866_a(World.java:1976)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1939)

-- Entity being ticked --
Details:
	Entity Type: pokecube_ml:pidove (pokecube.core.entity.pokemobs.GenericPokemob519)
	Entity ID: 43689
	Entity Name: Pidove
	Entity's Exact location: -200.48, 83.84, 1208.73
	Entity's Block location: World: (-201,83,1208), Chunk: (at 7,5,8 in -13,75; contains blocks -208,0,1200 to -193,255,1215), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Entity's Momentum: 0.02, 0.01, 0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	World:: WorldServer{LevelName=BOP Pokecube 54, DimensionId=0, DimensionType=minecraft:overworld}
	Owner:: 59838dcc-8b8e-4fa0-9af2-36141389bb0a
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6032)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2205)
[crash-2017-07-17_05.34.05-server.txt](https://github.com/Thutmose/Pokecube/files/1152132/crash-2017-07-17_05.34.05-server.txt)
`

#### What you expected to happen:
Not to randomly crash

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:6.5.3
- Pokecube Revival (if applicable):6.4
- Pokecube Mobs (if applicable):2.7.2
- Minecraft: 1.12
- Forge:14.21.1.2431

**Comment by Thutmose** [comment] 2017-07-17 16:16
I will get this looked into, thanks for including the crash report.

**Comment by Thutmose** [comment] 2017-07-17 16:20
This seems to be an issue somehow related to sponge, can you see if you can get it replicated in an environment without sponge?

The crash is caused by something going wrong when defeating a pokemob owned by either an NPC or an offline player.

**Comment by Thutmose** [comment] 2018-01-18 23:27
due to massive changes in sponge since this issue was released, the stuff it in won't really help much anymore, so I am closing this one, If it still occurs, remake the issue using the latest sponge/pokecube.

**Closed as completed by Thutmose** 2018-01-18 23:27 UTC
Labels: Major Bug, Compatiblity Issue, SPONGE
