### ISSUE TITLE
Pokecubes Inventory Bug?

### ISSUE THREAD

**Issue by Shemychu** [Thutmose/Pokecube#206] opened 2017-08-02 19:04 UTC
#### Issue Description:
Can't open Pokecubes inventory via "right clicking" as instructed. - This is occurring on a multiplayer server.

#### What happens:
Nothing opens.

#### What you expected to happen:
Inventory to open.

#### Steps to reproduce:

1. Throw out Pokemon
2. Right click
3. Profit?
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: - 4.35.0
- Pokecube Revival - 4.22.2
- Pokecube Mobs - 2.14.0
- Minecraft: 1.10.2
- Forge: Sponge 1.10.2-2281-5.2.0-BETA-2274.jar

**Comment by Thutmose** [comment] 2017-08-02 19:09
this is a duplicate of #202 

It is caused by this: https://github.com/SpongePowered/SpongeForge/issues/1689

Spongeforge needs to fix this on their side.

**Closed as completed by Thutmose** 2017-08-02 19:09 UTC
Labels: duplicate
