### ISSUE TITLE
PokecubeTable/Trading Table Issues

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#69] opened 2016-06-25 22:18 UTC
#### Issue Description:
The Trading Table and Pokecube Table

#### What happens:
Neither one of these devices can be mined for removal.  The pokecube table appears to have no function, which could be due to lack of user knowledge, or genuine lack of function.

#### What you expected to happen:
To be able to move these blocks.

#### Steps to reproduce:

Set either device, try to mine.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.3.2
- Pokecube Revival (if applicable):3.3.2
- Pokecube Mobs (if applicable):2.1.2
- Minecraft: 1.9.4 Server
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment] 2016-06-25 22:27
Trading table can be broken, it just takes a rather long time.

The Pokecube Table is an alternate way to get the choose first gui.  If the gui doesn't show up on first join (or you click escape to exit it) you can re-open it by right clicking the Pokecube table.

Also, if you put an inventory 2 under the pokecube table and fill it with eggs, the pokemobs in the eggs are available as starters (way for server to set custom starters)

**Comment by XileForce** [comment] 2016-06-26 01:06
A bit off topic, but when people haven't had the gui launch for whatever reason, using the table doesnt seem to bring it up either.

**Comment by Thutmose** [comment] 2016-06-26 01:12
hmm, Is there any pattern as to what makes it not occur? 
Had they been on a single player world first?

One workaround is normally to relog from server.

**Comment by XileForce** [comment] 2016-06-26 01:15
That I do not know. Ill report an issue if I find a pattern. Luckily relogging always works, just wasn't sure if the table itself currently works.

**Comment by Thutmose** [comment] 2016-06-26 01:27
oh, to test the table, press escape when you get the gui, and the table should have a pokecube rendered on it, if you right click it, it brings back up the gui

**Comment by doctorkreger** [comment] 2016-06-27 15:17
On the trade table, it appears that we are unable to process trades.  The slots on the table won't accept cubes, so you cannot put anything in the trading table.

**Comment by Thutmose** [comment] 2016-06-27 18:37
which version of pokecube?

**Comment by XileForce** [comment] 2016-06-27 18:48
Yea this bug has been happening since we started using the mod. But we can't seem to find out how to reproduce it. The table will work fine for awhile then stop and you have to break it and place it again to make it work.

**Comment by schindlershadow** [comment] 2016-06-28 02:22
I did some tests, looks like when the chunk with the table in it is unloaded then loaded the issue occurs.

**Comment by Thutmose** [comment] 2016-06-28 02:33
confirmed that is how to replicate the issue. I will work on fixing it asap.

**Comment by Thutmose** [comment] 2016-06-28 02:44
I have a possible fix done, I am testing it, and if I can no longer replicate this, I will upload a new release with it.

**Comment by Thutmose** [comment] 2016-06-28 02:51
The fixes for this have been uploaded as Pokecube Core 3.3.8/4.0.8, I will leave this issue open to cover any issues with the Pokecube Table as well (incase we ever find a way to replicate the no gui issue)

**Comment by Thutmose** [comment] 2016-09-14 18:29
Wiki for this should be up sometime soon, so closing this issue.

**Closed by Thutmose** 2016-09-14 18:29 UTC
Labels: question
