### ISSUE TITLE
[1.12.2] Invisible pokemon

### ISSUE THREAD

**Issue by Kingluna747** [Thutmose/Pokecube#238] opened 2017-12-19 02:02 UTC
#### Issue Description: a lot of pokemon are Invisible in 1.12.2, including Lunala and Solgaleo, and a lot of other pokemon too, a lot of my favorites, even my most favorite of all is invisible Glaceon, please do something its driving me crazy invisible pokemon galore, i'd like to start up a world where me and some friends can be the PES (Pokémon Expedition Society)  so we can use the metanorph mod to morph into PES pokemon  but some of them are invisible, Ampharos is the most important PES pokemon coz he's their Chief but ampharos is invisible, some of the I can see, like buizel, mawile, and Dedenne, I dunno bout bunnelby, Jirachi, archen and swirlix though, i can see Kangaskhan, in pokemon super mystery dungeon she runs the Café Connection (or as i call it Connection Café) i can't even find Hawlucha, i can see Keckleon who runs the keckleon shop, Cofagrigus is invisible and we need him coz he runs glorious gold i think it is, i can see lapras so she's ok she runs the lapras liner, Klefki is there and i can see her, she runs the place that opens treasure boxes, Hawlucha runs Hawlucha's Slam School, i can see meowth he runs Meowth Theater, Samurott and Serperior are invisible too and i really need them too coz i started pokemon super mystery dungeon with oshawott and snivy now I'm Samurott and my partner pokemon is superior so i really need them too, all the evolved forms of eevee are invisible too, eevee isn't though, i dunno if anyone else can see any of the ones that are invisible for me or not but anyways i really need all these pokemon yet most of them are invisible, please can you please do something about it for me
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.12.2
- Forge:

**Comment by smmmadden** [comment] 2017-12-19 02:41
fwiw, I do not see this issue in 1.12.2. :-)  You stated 1.8.9 in the description, so which version are you on and what version of Forge or Sponge Forge are you using?  What version of Pokecube Core, Revival and Mobs are you using?  The developer can't help unless you provide all the details.

**Comment by Thutmose** [comment] 2017-12-19 02:51
ya, I need versions and more details, especially which other mods you are using

**Comment by Kingluna747** [comment] 2017-12-20 03:44
i'm only new here so I'm not really sure of some things yo, but I'm on minecraft 1.12.2, and forge mod loder 8.0.99.99, minecraft forge 14.23.0.2491, I did say about the metamorph mod which it says it's metamorph 1.1.4-1.12, Pokecube Revival-6.13.2, Pokecube Mobs-4.1.2, Pokecube Core-6.23.3, and thutcore-5.11.7  I have tried with and without other mods but I still have the same problem, yeah so I dunno what is going on, but look I love your mod, it's the best mod ever, is there anything else I need to tell you coz like I said i'm only new on here

**Comment by smmmadden** [comment] 2017-12-20 04:57
First I would suggest updating the modes and Forge so that they match up.  One thing that you will learn is that each mod that is created is tested on specific versions and when bugs are reported they get fixed in later ones.  So keeping current is important.  So here are some details to help that I'm not able to reproduce the issue you reported.  So I'd start by getting the latest version or at least these.
Pokecube Core: 6.27.7.b
Pokecube Mobs: 4.1.6
Pokecube Revival 6.13.12
ThutCore: 5.12.5
ThutBling: 2.0.2 (not required)
ThutWearables: 3.1.3 (not required)
Along with this, I use Sponge Forge 1.12.2-2555-7.0.0-BETA-2761
And OptiFine_1.12.2_HD_U_C6

**Comment by Kingluna747** [comment] 2017-12-20 04:59
ok cool thanks I will try that

**Comment by Thutmose** [comment] 2017-12-20 05:09
I would greatly suggest using the twitch client for managing the mods, it will have a little icon to indicate whether a mod is outdated:
![image](https://user-images.githubusercontent.com/2363472/34192086-cd17632a-e519-11e7-9580-cb359f085367.png)

the latest versions of the pokecube mods are:
Core: 6.30.3
Revival: 6.13.16
Mobs: 4.2.2
ThutCore: 5.13.0 (.c, but the alphabetical ones are mostly minor tweaks)

These are tested on forge 2555.

**Comment by Kingluna747** [comment] 2017-12-20 05:11
thank you

**Comment by Thutmose** [comment] 2017-12-20 05:11
I don't know about metamorph, but for some customnpcs stuff, it requires setting preload to true in pokecube_ml.cfg, this increases the initial startup time of the mod, as well as the ram use, but it fixes some strange issues with customnpcs rendering of mobs.

**Comment by Kingluna747** [comment] 2017-12-20 05:13
metamorph lets you morph into any mob including ones from other mods

**Comment by Thutmose** [comment] 2017-12-20 05:17
there is a mod for turning into pokemobs specifically, it is called pokeplayer (https://minecraft.curseforge.com/projects/pokeplayer), i think it might have some bugs with move use in the very latest versions though, If I get time, I can see about getting those bugs worked out. I am mostly waiting for someone to offer to help maintain it.

**Comment by smmmadden** [comment] 2017-12-20 05:32
I've also created a modpack for the [Technic Launcher](https://www.technicpack.net/modpack/edit/1124691/main) which does a great job with updates and installs too.

**Comment by Thutmose** [comment] 2017-12-20 05:34
Does that check curseforge for latest versions of mods? The twitch one checks for mod updates as well as pack updates

**Comment by smmmadden** [comment] 2017-12-20 05:39
Not that I'm aware of.  The way I have it setup is to match my servers so that there are no incompatibilities between the client and server-side mods.  But it does sound like a good idea to offer on both sites.

**Comment by Thutmose** [comment] 2017-12-20 05:42
By default the twitch packs are "locked" and only show pack updates rather than mod updates, the is a button in options to unlock them.

Custom packs are not locked by default, and are very useful for checking for mod updates

**Comment by Kingluna747** [comment] 2017-12-20 07:01
you have been a really big help thank you

**Comment by Kingluna747** [comment] 2017-12-20 07:01
it all works like a charm now

**Comment by Kingluna747** [comment] 2017-12-20 07:04
that's pretty cool I like how wobbuffet looks a bit like a creeper, that's so cool yo

**Comment by Kingluna747** [comment] 2017-12-20 07:11
oh also do you know of any yugioh mods or sonic the hedgehog mods that might work for me too?

**Comment by P3rf3ctXZer0** [comment] 2017-12-20 20:12
Sonic Mod was 1.7.10 @Kingluna747 but I have never seen a Yu-Gi-Oh Mod. I know at one point there was a MTG mod being made and I know a Zelda mod is in the work there was also a Metroid mod and Kingdom hearts mod that was very buggy for 1.7.10 fandom mods are often buggy and unstable infact the most stable fandom mod is pokecube.

**Comment by Kingluna747** [comment] 2017-12-21 04:54
is there anyone who could make a yugioh mod that the rules set and ability sets is based on the YuGiOh Zexal anime tv show, coz yugioh zexal is my faveorite yugioh but of course it would be good to have every card in it that there is and ever was, I have an idea of how it could work too, like it would be great if it all works like it dose in the tv show, to start it could ask you who your faveorite yugioh character is out of all the main characters (mine is Yuma from yugioh zexal) and based on who you pick it will give you a starter deck from that charater, and it could add NPC duelists that you can duel against and win a card if you win the duel, plus you could find hidden chests with a special card in it like from rare or better range and in dungeons you could find like a common or uncommon card, m(and the number cards need the number ability too where in most situations the only way to destroy a number by battle is to use another number) coz I think it would be pretty cool, of course I would chose Yuma as my favorite character so it would give me a Yuma starter deck which would have to include Gagaga Magician and Gagaga Girl in it along with all kinds of other cards Yuma first started with, and his go to XYZ monster too which is Number 39 Utopia (that is that one in the Extra Deck of course), it would be a great idea and a lot of people love yugioh and minecraft so it would make them happy as happy can be happy, but of course there can also be a twist where every starter deck could also contain a new LINK Monster, so far my most favorite LINK Monster is Imduk the World Chalice Dragon, the Yuma starter deck could have that in it and it needs a normal monster to go with it, it`s ability is,
During your main phase you can normal summon 1 World Chalice monster in addition to your normal summon/set (you can only gain this effect once per turn) at the start of the damage step, if this card battles an opponent`s monster this card points to; you can destroy that opponent`s monster. If this card is sent from the field to the GY(Graveyard) you can special summon 1 world chalice monster from your hand. and before it says it`s ability it has on it 1 Normal Monster, except a Token, I`m just not sure if that means you have to tribute 1 normal monster to summon Imduk the World Chalice Dragon or if you have to summon 1 Normal Monster to summon Imduk the World Chalice Dragon, I don't know if link cards even have a defence mode coz there isn't even DEF there instead it just has the ATK then next to it it has LINK - 1 (at least that's what Imduk the World Chalice Dragon has anyways) its a [Dragon/Link/Effect] monster, I have never even heard of them, I only just obtained it yesterday meaning 20/12/2017 by me coz I'm in Australia, well anyways yes I think the idea of a let's say All Yugioh mod or All things Yugioh mod, would be pretty cool it would be great, there could also even be spawn eggs to spawn monsters too and make them mobs too, that would be neat and add like a multi biome biome where it could be the only place where yugioh monsters could spawn naturally and their behaviour of every monster while not passive not aggressive either, for example if you attack a yugioh monster it will attack you, and you could tame a yugioh monster by giving it a blank card which you can then use in a duel because the blank card will then become a copy of that monster card, of course you could also let them out to feed them and so they can play and protect you from other yugioh monsters should one attack you,and in battle outside a duel the winner wouldn't always be the one with higher ATK, each yugioh monster can have it's own healh or Life Points as it is in yugioh and LP for short just as GY is short of Graveyard it would only be in a actual duel where the one with higher ATK wins the battle, of course you would get a starter deck from the favorite character you chose it would also give you a case to store all your cards in a well as a belt with the extra deck to wear by putting it in a new slot it could add for yugioh belts and it could add a slot for your arm where the duel disk goes coz it would give you the belt and duel disk too, and it would also give you a instruction book for those who have never played yugioh before, in the book would be the rule set and well pretty much info to tell you how it all works maybe, like well ya know so you know how to use the duel disk and the cards and stuff like that

**Comment by Thutmose** [comment] 2017-12-21 15:51
Closing this issue since the problem it was made for seems to have been dealt with

**Closed as completed by Thutmose** 2017-12-21 15:51 UTC
Labels: Cannot Replicate
